### ISSUE TITLE
What is the minimum iOS Version that can run SwiftUICharts?

### ISSUE THREAD

**Issue by UncleRic** [willdale/SwiftUICharts#41]
My Xcode says it's iOS 14.0.
I was hoping for iOS 13.0 for my iPhone 6s Plus.

**Comment by willdale** [comment]
iOS 14.0.

What version of charts are you using?

There are a couple things used that are only available in iOS 14.

All the accessibility uses the iOS 14 APIs rather than the now deprecated iOS 13 ones.

It looks like all the issues are surmountable it's just I'm not sure if or when I'll have time to look at it.

**Comment by UncleRic** [comment]
I'm okay at my end.
Thanks.
